<?php
namespace backend\controllers;

use Yii;
use yii\web\Controller;

class PublicController extends Controller
{
    public function beforeAction($action)
    {
        if (!parent::beforeAction($action)) {
            return false;
        }

        if (Yii::$app->user->isGuest){
            //return $this->goHome()->send();//这边需要家send(),不然无法跳转，Yii 2.0.7
            return $this->goHome();
        }

        return true;
    }

    public function afterAction($action, $result)
    {
        return parent::afterAction($action, $result); // TODO: Change the autogenerated stub
    }
}