<?php
namespace frontend\controllers;

class BlogController extends PublicController
{
    /**
     * @return array
     */
    public function behaviors()
    {
        return parent::behaviors(); // TODO: Change the autogenerated stub
    }

    /**
     * @return string
     */
    public function actionIndex(){
        return $this->render('index');
    }

    /**
     * @return string
     */
    public function actionArticle(){
        return $this->render('article');
    }
}