<?php
/**
 * Created by PhpStorm.
 * User: vlson
 * Date: 2019/5/5
 * Time: 15:20
 */

namespace frontend\controllers;


class BlogController extends PublicController
{
    /**
     * @return array
     */
    public function behaviors()
    {
        return parent::behaviors(); // TODO: Change the autogenerated stub
    }

    public function actionIndex(){
        return $this->render('index');
    }

    public function actionArticle(){
        return $this->render('article');
    }
}