<?php
namespace frontend\controllers;

use Yii;
use yii\web\Controller;

class PublicController extends Controller{
    public function beforeAction($action)
    {
        $controller = $action->controller->id;
        $page = $action->id;
        if($controller == 'blog' && $page == 'article'){
            $ip = Yii::app()->request->userHostAddress;
            echo $ip;
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function afterAction($action, $result)
    {
        return parent::afterAction($action, $result); // TODO: Change the autogenerated stub
    }
}